### ISSUE TITLE
Failed to activate the atom-template-engine package

### ISSUE THREAD

**Issue by gmodzelewski** [michealbenedict/atom-template-engine#1]
[Enter steps to reproduce below:]
1. update and restart
2. fail

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-template-engine](https://github.com/rowoot/atom-template-engine) package, v0.2.2
### Stack Trace

Failed to activate the atom-template-engine package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at /Users/georgmodzelewski/.atom/packages/atom-template-engine/lib/atom-template-engine.js:53:25
  at Array.forEach (native)
  at Object.plugin.activate (/Users/georgmodzelewski/.atom/packages/atom-template-engine/lib/atom-template-engine.js:52:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:623:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:54:25)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autoflow",
      "pretty-json",
      "preview",
      "wrap-guide"
    ],
    "themes": [
      "atom-light-ui",
      "monokai-light"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.1.0
atom-template-engine, v0.2.2
atom-ternjs, v0.5.23
autocomplete-plus, v2.12.0
color-picker, v1.4.4
html2jade, v0.7.0
language-jade, v0.3.0
merge-conflicts, v1.2.10
minimap, v4.3.1
monokai-light, v0.3.6
node-resolver, v1.0.1
valign, v0.13.4

# Dev
No dev packages
```

**Comment by gmodzelewski** [comment]
+1

**Comment by findfly618** [comment]
+1

**Comment by findfly618** [comment]
activate failed

**Comment by chenleo** [comment]
+1

**Comment by medialwerk** [comment]
+1

**Comment by odikusar** [comment]
+1

**Comment by abiodun0** [comment]
+1

**Comment by mrkam** [comment]
+1

**Comment by pwsm50** [comment]
+1

**Comment by stanwmusic** [comment]
+1
This is a  new install I have only used twice briefly so far.  I had very few problems with the old version.
This issue is no biggie to me, I only posted this in case it helps someone.

---

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 14.04.5
**Thrown From**: [atom-template-engine](https://github.com/rowoot/atom-template-engine) package, v0.2.2

### Stack Trace

Failed to activate the atom-template-engine package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at /home/stan/.atom/packages/atom-template-engine/lib/atom-template-engine.js:53:25
  at Array.forEach (native)  
  at Object.plugin.activate (/home/stan/.atom/packages/atom-template-engine/lib/atom-template-engine.js:52:6)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
  at /usr/share/atom/resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at /usr/share/atom/resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
  at /usr/share/atom/resources/app.asar/src/atom-environment.js:765:28

```

### Commands

```
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
angular-bootstrap, v1.0.1 (inactive)
angular2-snippets, v0.3.0 (inactive)
angularjs-snippets, v0.10.18 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-bootstrap4, v1.4.0 (inactive)
atom-html-preview, v0.1.22 (inactive)
atom-template-engine, v0.2.2 (inactive)
atom-templatebuilder-tools, v0.7.2 (inactive)
atom-webbrowser, v2.1.4 (inactive)
best-js-snippets, v4.1.0 (inactive)
bootstrap-3-snippetset, v0.0.6 (inactive)
bootstrap3-snippets, v0.1.2 (inactive)
bootstrap4-snippets, v0.2.2 (inactive)
css-from-html, v0.1.5 (inactive)
css-snippets, v1.0.0 (inactive)
django-templates, v0.5.0 (inactive)
export-html, v3.0.0 (inactive)
file-templates, v0.2.0 (inactive)
html-head-snippets, v0.2.0 (inactive)
html-to-css, v0.2.2 (inactive)
HTML2JS, v0.2.1 (inactive)
htmlhint, v1.1.4 (inactive)
js-extras, v1.4.0 (inactive)
open-in-browser, v0.4.7 (inactive)
package-list, v0.1.2 (inactive)
scss-snippets, v0.2.0 (inactive)
template-insert, v2.0.3 (inactive)
v-bootstrap4, v0.1.7 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.2 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by angelxaces** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-template-engine](https://github.com/rowoot/atom-template-engine) package 0.2.2


### Stack Trace

Failed to activate the atom-template-engine package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at /packages/atom-template-engine/lib/atom-template-engine.js:53:25
    at Array.forEach (native)
    at Object.plugin.activate (/packages/atom-template-engine/lib/atom-template-engine.js:52:6)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
angular-bootstrap 1.0.1 
angularjs 0.4.0 
angularjs-boilerplate-snippets 0.3.1 
atom-bugs 0.24.0 
atom-ci-snippets 0.5.0 
atom-commander 0.8.7 
atom-html-templates 0.1.3 
atom-json-editor 0.4.1 
atom-package-manager 1.15.2 
atom-react-native-css 1.1.3 
atom-smart-template 0.3.2 
atom-template-engine 0.2.2 
atomic-chrome 0.3.0 
bootstrap-3-snippets-for-atom 1.3.0 
cdn-libs 0.1.2 
code-annotations 2.1.3 
code-links 0.4.0 
code-peek 1.4.16 
codeigniter 0.3.2 
codeigniter-nucleus 0.4.3 
codeigniter-utilities 0.2.0 
command-executor 1.4.3 
command-toolbar 1.0.12 
dev-tools-themes 0.1.3 
file-templates 0.2.0 
git-control 0.8.2 
git-plus 7.3.3 
git-plus-plus 1.1.0 
git-projects 1.17.0 
gravitate-snippets 0.9.0 
hyperclick 0.0.40 
icon-fonts 2.15.1 
intellij-idea-keymap 0.2.3 
javascript-snippets 1.2.1 
js-hyperclick 1.10.1 
js-patterns-atom-snippets 0.2.1 
language-javascript-jsx 0.3.7 
ll-php-support 0.1.3 
map-queries 0.5.0 
menu-manager 0.6.0 
minimap 4.26.8 
modal-file-manager 0.3.1 
node-debug 0.1.7 
node-debugger 1.10.1 
node-on-fire 0.1.0 
open-iconic 1.1.1 
package-list 0.1.2 
package-manager-commands 2.0.3 
php-debug 0.2.4 
php-fmt 0.1.2 
php-hyperclick 1.2.1 
php-server 0.7.0 
project-manager 3.3.3 
project-sidebar 1.3.0 
Quick-JavaScript 2.2.0 
rawn-snippets 0.1.5 
react 0.16.2 
seti-icons 1.3.4 
sync-settings 0.8.1 
ui 0.2.0 
xml-formatter 0.10.0 
xml-tools 0.2.1 
```

**Comment by stanwmusic** [comment]
+1 this came up when I opened Atom
